version = 0.1

# === Default (dev) ===
[default]
[default.global.parameters]
stack_name = "fleet-command-dev"
region = "us-east-2"

[default.deploy.parameters]
parameter_overrides = "Environment=dev"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true

# === Prod ===
[prod]
[prod.global.parameters]
stack_name = "fleet-command-prod"
region = "us-east-2"

[prod.deploy.parameters]
parameter_overrides = "Environment=prod"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
