import { useState, useRef, useEffect } from 'react';
import { WORKER, VCAT } from '../lib/constants';
import { fmtDate, stColor, stLabel, vData } from '../lib/utils';
import { S } from '../lib/styles';
import { DateIn } from './DateIn';
import { useStore, selectRoles } from '../lib/store';

export function ReconCategory({cat,task,vOpts,onAssign,onEst,onApr,onStart,onCmp,onTog,onNotes,onPhotos,onOrder,onUpdVendor,onSelectVendor,onSendReminder,onReassign,canEditRecon,onUpdateTask}: any){
const notify = useStore((s: any) => s.notify);
const fireEmail = useStore((s: any) => s.fireEmail);
const currentUser = useStore((s: any) => s.currentUser);
const vehicle = useStore((s: any) => s.selV);
const deepLinkCat = useStore((s: any) => s.deepLinkCat);
const setDeepLinkCat = useStore((s: any) => s.setDeepLinkCat);
const { isAdmin, isVendor } = useStore(selectRoles);
const buyingBroker = vehicle?.buyingBroker || "";
const isGrounded = !!(vehicle?.transport?.inbound?.delivered && !vehicle?.arb?.open);
const usedOrders = VCAT.filter((c: any) => c.key !== cat.key && vehicle?.reconTasks?.[c.key]?.order).map((c: any) => vehicle?.reconTasks?.[c.key]?.order);
const autoExpand = deepLinkCat === cat.key;
const onClearDeepLink = () => setDeepLinkCat(null);
const [ei,setEi]=useState("");const [no,setNo]=useState(false);const [nv,setNv]=useState(task?.notes||"");const [po,setPo]=useState(false);const [exp,setExp]=useState(autoExpand||false);const fr=useRef(null as any);
const [startEta,setStartEta]=useState("");const [lbImg,setLbImg]=useState(null as any);const [editBid,setEditBid]=useState(false);
useEffect(()=>{if(autoExpand){setExp(true);setTimeout(()=>{if(fr.current)fr.current.scrollIntoView({behavior:"smooth",block:"center"});},200);}},[autoExpand]);
const cl=stColor(task?.status||"na"),need=task?.needed,photos=task?.photos||[];const isOEM=cat.key==="oemdealer";
const uploadVid=async(f: any)=>{try{const fd=new FormData();fd.append("file",f);const r=await fetch(WORKER+"/api/uploads",{method:"POST",headers:{Authorization:"Bearer "+(sessionStorage.getItem("fc_token")||"")},body:fd});const j=await r.json();return j.ok?j.data.url:URL.createObjectURL(f);}catch{return URL.createObjectURL(f);}};
const hu=async(e: any)=>{const fs=Array.from(e.target.files||[]);if(!fs.length)return;const np:any[]=await Promise.all((fs as File[]).map(async(f:File)=>{const isVid=f.type.startsWith("video");if(isVid)return {data:await uploadVid(f),name:f.name,date:new Date().toISOString().split("T")[0],type:"video"};return {data:"pending",blob:f,name:f.name,date:new Date().toISOString().split("T")[0],type:"image"};}));const imgs=np.filter(x=>x.type==="image");const vids=np.filter(x=>x.type==="video");if(imgs.length===0){onPhotos([...photos,...vids]);e.target.value="";return;}await Promise.all(imgs.map((item: any)=>new Promise(r=>{const rd=new FileReader();rd.onload=()=>{item.data=rd.result;r(item);};rd.readAsDataURL(item.blob);})));onPhotos([...photos,...imgs,...vids]);e.target.value="";};
const sv=(task?.vendors||[]).find((v: any)=>v.selected)||(task?.vendors||[])[0]||null;
return <span style={{display:"contents"}}>{!exp?<div ref={fr} style={{...S.card,borderLeft:`4px solid ${cl.bd}`,background:cl.bg,opacity:need?1:0.5,cursor:"pointer",minHeight:50}} onClick={()=>setExp(true)}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div style={{display:"flex",alignItems:"center",gap:8}}>
{need&&<select style={{width:32,height:24,borderRadius:4,border:"1px solid rgba(255,255,255,0.2)",background:"rgba(255,255,255,0.1)",color:"#FFF",fontSize:12,fontWeight:800}} value={task?.order||""} onClick={(e: any)=>e.stopPropagation()} onChange={(e: any)=>{e.stopPropagation();onOrder&&onOrder(e.target.value);}}>
<option value="">—</option>{[1,2,3,4,5,6,7,8,9,10].map(n=><option key={n} value={n} disabled={(usedOrders||[]).includes(n)&&task?.order!==n}>{n}{(usedOrders||[]).includes(n)&&task?.order!==n?" ✗":""}</option>)}</select>}
<span style={{fontSize:20}}>{cat.icon}</span><span style={{fontWeight:700,color:"#E5E7EB",fontSize:16}}>{cat.label}{task?.noteUnread&&<span style={{marginLeft:6,fontSize:10,background:"#F59E0B",color:"#000",borderRadius:10,padding:"2px 6px",fontWeight:700}}>🔔</span>}</span></div>
<div style={{display:"flex",alignItems:"center",gap:6}}>
<span style={{...S.badge,background:cl.bd,color:cl.text,fontSize:11}}>{stLabel(task?.status||"na")}</span>
<label style={{fontSize:12,color:"#6B7280",display:"flex",alignItems:"center",gap:4}} onClick={(e: any)=>e.stopPropagation()}>
{need&&(task?.status==="complete"||task?.status==="started"||task?.status==="approved"||(task?.completedRounds||[]).length>0)?<span>🔒</span>
:<input type="checkbox" checked={need||false} onChange={onTog}/>} Need</label></div></div>
{need&&sv&&<div style={{marginTop:4}}><span style={{fontSize:14,fontWeight:700,color:"#FFF"}}>{sv.name}</span><span style={{color:"#FBBF24",marginLeft:8}}>${(()=>{const acceptedTotal=(sv.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);if(acceptedTotal>0)return acceptedTotal.toLocaleString();const bidTotal=(sv.lineItems||[]).filter((x: any)=>!x.declined).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);return bidTotal.toLocaleString()+(sv.bidLocked&&task?.status==="estimated"?" pending":"");})()}</span></div>}
{need&&!sv&&(task.completedRounds||[]).length>0&&<div style={{marginTop:4,fontSize:12,color:"#F97316"}}>🔄 Round {(task.completedRounds||[]).length+1} — assign vendor</div>}
{need&&(task.completedRounds||[]).length>0&&<div style={{marginTop:2}}>{(task.completedRounds||[]).map((rd: any,ri: any)=><div key={ri} style={{fontSize:10,color:"#34D399"}}>✅ R{ri+1}: {rd.tasks||"completed"} — ${rd.cost||0}{rd.vendor?" — "+rd.vendor:""}</div>)}</div>}
{need&&(()=>{const vs=task.vendors||[];const dec=vs.filter((v2: any)=>v2.declined).length;return dec>0?<div style={{fontSize:12,color:"#FCA5A5",marginTop:2}}>❌ {dec}/{vs.length} vendors declined</div>:null;})()}
{need&&sv&&(cat.key==="parts"||(task.workTasks||[]).some((w: any)=>w.isPart))&&(()=>{const wt2=task.workTasks||[];const pts2=(cat.key==="parts"?wt2:wt2.filter((w: any)=>w.isPart)).filter((w: any)=>{const li9=(sv.lineItems||[]).find((x: any)=>x.id===w.id)||{};return !li9.declined&&li9.accepted;});if(!pts2.length)return null;return <div style={{marginTop:4}}>{pts2.map((w: any)=>{const li2=(sv.lineItems||[]).find((x: any)=>x.id===w.id)||{};const st=li2.partInstalled?"✅ Installed":li2.partArrived?"📦 Arrived":li2.partOrdered?"🔄 Ordered":"⏳ Pending";const dt=li2.partInstalled?li2.partInstalledDate:li2.partArrived?li2.partArrivedDate:li2.partOrdered?li2.partOrderedDate:"";const clr=li2.partInstalled?"#34D399":li2.partArrived?"#60A5FA":li2.partOrdered?"#FBBF24":"#6B7280";return <div key={w.id} style={{fontSize:11,color:clr}}>{st} {w.desc}{dt?" — "+fmtDate(dt):""}</div>;})}</div>;})()}
{need&&task?.status==="started"&&task?.etaComplete&&<div style={{fontSize:12,color:"#FBBF24",marginTop:2}}>ETA: {fmtDate(task.etaComplete)}</div>}
{need&&task?.status==="complete"&&task?.dateCompleted&&<div style={{fontSize:12,color:"#34D399",marginTop:2}}>Completed: {fmtDate(task.dateCompleted)}</div>}
{need&&(task?.workTasks||[]).length>0&&<div style={{fontSize:11,color:"#9CA3AF",marginTop:2}}>{(()=>{const wt=task.workTasks||[];const activeTasks=wt.filter((w: any)=>{const li=(sv?.lineItems||[]).find((x: any)=>x.id===w.id)||{};return !li.declined;});const done=activeTasks.filter((w: any)=>{const li=(sv?.lineItems||[]).find((x: any)=>x.id===w.id);return li?.taskDone;}).length;const rds=(task?.completedRounds||[]).length;return done===activeTasks.length&&activeTasks.length>0?<span style={{color:"#34D399"}}>✅ All {activeTasks.length} tasks done{rds>0?" (R"+(rds+1)+")":""}</span>:<span>{done}/{activeTasks.length} tasks done{rds>0?" (R"+(rds+1)+")":""}</span>;})()}</div>}
</div>:null}
{exp&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,padding:20}} onClick={()=>setExp(false)}>
<div style={{background:"#12122A",border:`2px solid ${cl.bd}`,borderRadius:12,padding:24,width:"95%",maxWidth:800,maxHeight:"90vh",overflowY:"auto"}} onClick={(e: any)=>e.stopPropagation()}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
<div style={{display:"flex",alignItems:"center",gap:10}}>
<span style={{fontSize:32}}>{cat.icon}</span><span style={{fontWeight:800,color:"#E5E7EB",fontSize:22}}>{cat.label}</span>
<span style={{...S.badge,background:cl.bd,color:cl.text,fontSize:14,padding:"4px 12px"}}>{stLabel(task?.status||"na")}</span></div>
<button style={{...S.sm,fontSize:18}} onClick={()=>setExp(false)}>✕</button></div>
<div>
{!isOEM&&<div style={{marginBottom:12,padding:14,background:"#0D0D1A",borderRadius:8,border:"1px solid #2A2A3E"}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}>
<span style={{fontSize:16,fontWeight:700,color:"#E5E7EB"}}>📋 Work Tasks</span>
<div style={{display:"flex",gap:6}}>
{cat.key==="mechanical"&&!(task.workTasks||[]).some((w: any)=>w.desc==="Full Inspection")&&(!task.status||task.status==="unassigned"||task.status==="assigned")&&<button style={{...S.sm,color:"#F97316",border:"1px solid #F97316"}} onClick={()=>{const wt2=[...(task.workTasks||[]),{id:`wt${Date.now()}`,desc:"Full Inspection",isPart:false,isInspection:true}];const vs=(task.vendors||[]).map((vn: any)=>({...vn,lineItems:wt2.map((w: any)=>{const ex=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return ex?{...ex,desc:w.desc,isPart:w.isPart}:{id:w.id,desc:w.desc,price:0,isPart:w.isPart};})}));onUpdateTask({workTasks:wt2,vendors:vs});}}>🔍 Request Inspection</button>}
{(!task.status||task.status==="unassigned"||task.status==="assigned")?<button style={{...S.sm,color:"#3B82F6"}} onClick={()=>{const wt=[...(task.workTasks||[]),{id:`wt${Date.now()}`,desc:"",isPart:false}];const vs=(task.vendors||[]).map((vn: any)=>({...vn,lineItems:wt.map((w: any)=>{const ex=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return ex?{...ex,desc:w.desc,isPart:w.isPart}:{id:w.id,desc:w.desc,price:0,isPart:w.isPart};})}));const extra: any={workTasks:wt,vendors:vs};if(task.status==="complete"){const sv9=(task.vendors||[]).find((x: any)=>x.selected);const prevCost=(sv9?.lineItems||[]).filter((x: any)=>x.accepted).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const prevTasks=(task.workTasks||[]).map((w: any)=>w.desc).join(", ");extra.status="started";extra.dateStarted=new Date().toISOString().split("T")[0];extra.roundPhotoStart=(task.photos||[]).length;extra.completedRounds=[...(task.completedRounds||[]),{date:task.dateCompleted,tasks:prevTasks,cost:prevCost}];}onUpdateTask(extra);}}>+ Add Task</button>:<span style={{fontSize:11,color:"#4B5563"}}>🔒 Locked</span>}</div></div>
{(task.workTasks||[]).length===0&&<div style={{fontSize:14,color:"#4B5563",textAlign:"center",padding:10}}>Add tasks for vendor to price</div>}
{(task.workTasks||[]).map((wt: any,wi: any)=><div key={wt.id} style={{display:"flex",gap:8,alignItems:"center",marginBottom:6}}>
<input style={{...S.fi,fontSize:15,padding:"10px 12px",flex:1}} placeholder="e.g. Paint Hood" value={wt.desc} onChange={(e: any)=>{const items=[...(task.workTasks||[])];items[wi]={...items[wi],desc:e.target.value};const vs=(task.vendors||[]).map((vn: any)=>({...vn,lineItems:items.map((w: any)=>{const ex=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return ex?{...ex,desc:w.desc,isPart:w.isPart}:{id:w.id,desc:w.desc,price:0,isPart:w.isPart};})}));onUpdateTask({workTasks:items,vendors:vs});}}/>
<label style={{display:"flex",alignItems:"center",gap:4,fontSize:13,color:wt.isPart?"#60A5FA":"#6B7280"}}><input type="checkbox" checked={wt.isPart||false} onChange={(e: any)=>{const items=[...(task.workTasks||[])];items[wi]={...items[wi],isPart:e.target.checked};const vs=(task.vendors||[]).map((vn: any)=>({...vn,lineItems:items.map((w: any)=>{const ex=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return ex?{...ex,isPart:w.isPart}:{id:w.id,desc:w.desc,price:0,isPart:w.isPart};})}));onUpdateTask({workTasks:items,vendors:vs});}}/>Part</label>
{(()=>{const hasVendors=(task.vendors||[]).length>0;const anyBid=(task.vendors||[]).some((vn2: any)=>(vn2.lineItems||[]).some((li2: any)=>li2.price>0||li2.accepted));const locked=hasVendors&&(anyBid||task.status==="started"||task.status==="complete"||task.status==="approved");return locked?<span style={{fontSize:14,color:"#4B5563",padding:"0 4px"}} title="Locked — vendor assigned">🔒</span>:<button style={{background:"none",border:"none",color:"#F87171",fontSize:18,cursor:"pointer"}} onClick={()=>{const items=(task.workTasks||[]).filter((_: any,j: any)=>j!==wi);const vs=(task.vendors||[]).map((vn: any)=>({...vn,lineItems:items.map((w: any)=>{const ex=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return ex||{id:w.id,desc:w.desc,price:0,isPart:w.isPart};})}));onUpdateTask({workTasks:items,vendors:vs});}}>✕</button>;})()}</div>)}</div>}
{isOEM&&need&&<div style={{padding:12,background:"#1A1A2E",borderRadius:8,border:"1px solid #78590A",marginBottom:10}}>
<div style={{fontSize:16,fontWeight:800,color:"#FDE68A",marginBottom:10}}>🏭 OEM Dealer Service</div>
<label style={{...S.fl,fontSize:14}}>Dealer Name *<input style={{...S.fi,fontSize:16,padding:"10px 14px"}} value={task.oemDealer||""} onChange={(e: any)=>{onUpdateTask({oemDealer:e.target.value})}} placeholder="e.g. Larry H Miller Toyota"/></label>
<label style={{...S.fl,fontSize:14,marginTop:8}}>Drop Off Date<div style={{display:"flex",gap:6}}>
<input style={{...S.fi,fontSize:16,padding:"10px 14px",flex:1}} type="date" value={task.oemDropDate||""} onChange={(e: any)=>onUpdateTask({oemDropDate:e.target.value,status:e.target.value?"assigned":"unassigned",vendorName:task.oemDealer||"OEM Dealer",dateAssigned:e.target.value||task.dateAssigned})}/>
</div></label>
{task.oemDropDate&&<div style={{fontSize:14,color:"#FBBF24",fontWeight:600,marginTop:4}}>📅 Dropped Off: {fmtDate(task.oemDropDate)}</div>}
<label style={{...S.fl,fontSize:14,marginTop:8}}>Problems / Concerns *<textarea style={{...S.fi,fontSize:14,minHeight:80,resize:"vertical"}} value={task.oemProblems||""} onChange={(e: any)=>onUpdateTask({oemProblems:e.target.value})} placeholder="Describe what needs to be looked at..."/></label>
{task.oemDropDate&&<div style={{marginTop:12}}>
<div style={{display:"flex",gap:8,marginBottom:10}}>
<button style={{flex:1,padding:12,borderRadius:8,cursor:"pointer",textAlign:"center",fontSize:15,fontWeight:700,border:task.oemPaidRepair?"2px solid #3B82F6":"2px solid #2A2A3E",background:task.oemPaidRepair?"#1E3A5F":"#0D0D1A",color:task.oemPaidRepair?"#93C5FD":"#6B7280"}} onClick={()=>onUpdateTask({oemPaidRepair:!task.oemPaidRepair})}>💰 Paid Repair</button>
<button style={{flex:1,padding:12,borderRadius:8,cursor:"pointer",textAlign:"center",fontSize:15,fontWeight:700,border:task.oemWarranty?"2px solid #166534":"2px solid #2A2A3E",background:task.oemWarranty?"#0D3B1E":"#0D0D1A",color:task.oemWarranty?"#34D399":"#6B7280"}} onClick={()=>onUpdateTask({oemWarranty:!task.oemWarranty})}>🛡️ Warranty — No Cost</button>
</div>
{task.oemWarranty&&<div style={{padding:12,borderRadius:8,background:"#0D3B1E",border:"2px solid #166534",marginBottom:8}}>
<div style={{fontSize:16,fontWeight:700,color:"#34D399"}}>🛡️ WARRANTY COVERED — $0</div>
<label style={{...S.fl,fontSize:13,marginTop:6}}>Warranty Notes<textarea style={{...S.fi,fontSize:13,minHeight:50,resize:"vertical",width:"100%",boxSizing:"border-box"}} value={task.oemWarrantyNotes||""} onChange={(e: any)=>onUpdateTask({oemWarrantyNotes:e.target.value})} placeholder="Recall #, warranty type, what's covered..."/></label>
</div>}
{(task.oemPaidRepair||(!task.oemWarranty&&!task.oemPaidRepair))&&<div>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}>
<span style={{fontSize:15,fontWeight:700,color:"#E5E7EB"}}>Dealer Estimate</span>
<button style={{...S.btn,fontSize:12,padding:"4px 10px",background:"#78590A"}} onClick={()=>{const items=[...(task.oemItems||[]),{id:"oi"+Date.now(),desc:"",price:0,accepted:false,declined:false,costType:""}];onUpdateTask({oemItems:items});}}>+ Add Line Item</button>
</div>
{(task.oemItems||[]).length===0&&<div style={{fontSize:13,color:"#F87171",padding:10,textAlign:"center"}}>⚠️ Add dealer estimate line items before proceeding</div>}
{(task.oemItems||[]).map((item: any,ii: any)=><div key={item.id} style={{padding:8,marginBottom:4,borderRadius:6,background:"#0D0D1A",border:"1px solid #2A2A3E"}}>
<div style={{display:"flex",gap:6,alignItems:"center",marginBottom:4}}>
<input style={{...S.fi,fontSize:14,padding:"6px 10px",flex:1}} placeholder="Work description" value={item.desc} onChange={(e: any)=>{const items=[...(task.oemItems||[])];items[ii]={...items[ii],desc:e.target.value};onUpdateTask({oemItems:items});}}/>
<input style={{...S.fi,fontSize:14,padding:"6px 10px",width:100,textAlign:"right"}} type="number" placeholder="$" value={item.price||""} onChange={(e: any)=>{const items=[...(task.oemItems||[])];items[ii]={...items[ii],price:Number(e.target.value)};onUpdateTask({oemItems:items});}}/>
<button style={{background:"none",border:"none",color:"#F87171",fontSize:16,cursor:"pointer"}} onClick={()=>{const items=(task.oemItems||[]).filter((_: any,j: any)=>j!==ii);onUpdateTask({oemItems:items});}}>✕</button>
</div>
<div style={{display:"flex",gap:4,alignItems:"center"}}>
{item.desc&&item.price>0?<span style={{display:"contents"}}>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:item.accepted?"2px solid #166534":"1px solid #2A2A3E",cursor:item.costType?"pointer":"not-allowed",fontWeight:700,background:item.accepted?"#166534":"transparent",color:item.accepted?"#6EE7B7":item.costType?"#6B7280":"#4B5563",opacity:item.costType?1:0.5}} onClick={()=>{if(!item.costType)return;const items=[...(task.oemItems||[])];items[ii]={...items[ii],accepted:true,declined:false};onUpdateTask({oemItems:items,status:"approved",dateApproved:new Date().toISOString().split("T")[0]});}}>✅ {item.accepted?"Accepted":"Accept"}</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:item.declined?"2px solid #7F1D1D":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:item.declined?"#7F1D1D":"transparent",color:item.declined?"#FCA5A5":"#6B7280"}} onClick={()=>{const items=[...(task.oemItems||[])];items[ii]={...items[ii],declined:true,accepted:false};onUpdateTask({oemItems:items});}}>❌ Decline</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:item.costType!=="retail"&&item.costType?"2px solid #1E3A5F":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:item.costType!=="retail"&&item.costType?"#1E3A5F":"transparent",color:item.costType!=="retail"&&item.costType?"#93C5FD":"#6B7280"}} onClick={()=>{const items=[...(task.oemItems||[])];items[ii]={...items[ii],costType:"ws"};onUpdateTask({oemItems:items});}}>W/S</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:item.costType==="retail"?"2px solid #164E63":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:item.costType==="retail"?"#164E63":"transparent",color:item.costType==="retail"?"#67E8F9":"#6B7280"}} onClick={()=>{const items=[...(task.oemItems||[])];items[ii]={...items[ii],costType:"retail"};onUpdateTask({oemItems:items});}}>🏪 Retail</button>
</span>:<span style={{fontSize:12,color:"#6B7280"}}>⚠️ Enter description and cost first</span>}
</div>
</div>)}
{(task.oemItems||[]).length>0&&<div style={{marginTop:8,paddingTop:8,borderTop:"2px solid #2A2A3E"}}>
<div style={{fontSize:16,fontWeight:800,color:"#E5E7EB"}}>Total: <span style={{color:"#FBBF24",fontSize:20}}>${(task.oemItems||[]).reduce((s: any,x: any)=>s+(x.accepted?Number(x.price)||0:0),0).toLocaleString()}</span> <span style={{fontSize:12,color:"#6B7280"}}>(accepted)</span></div>
{(()=>{const items=task.oemItems||[];const ws=items.filter((x: any)=>x.accepted&&x.costType!=="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const ret=items.filter((x: any)=>x.accepted&&x.costType==="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);return (ws>0||ret>0)?<div style={{display:"flex",gap:12,marginTop:4}}>{ws>0&&<span style={{fontSize:13,color:"#93C5FD",fontWeight:600}}>W/S: ${ws.toLocaleString()}</span>}{ret>0&&<span style={{fontSize:13,color:"#67E8F9",fontWeight:600}}>🏪 Retail: ${ret.toLocaleString()}</span>}</div>:null;})()}
</div>}
</div>}
</div>}
{task.oemDropDate&&((task.oemWarranty)||(task.oemItems||[]).some((x: any)=>x.accepted))&&!task.oemWorkStarted&&<button style={{...S.btn,width:"100%",background:"#78590A",color:"#FDE68A",padding:12,fontSize:16,marginTop:8}} onClick={(e: any)=>{e.target.disabled=true;onUpdateTask({oemWorkStarted:true,oemWorkStartedDate:new Date().toISOString().split("T")[0],status:"started",dateStarted:new Date().toISOString().split("T")[0]});
if(typeof fireEmail==="function")fireEmail("vendor_work_started",{buyer:vehicle?.buyingBroker||"Buyer",vendor:{name:task.oemDealer||"OEM Dealer"},vehicle:vData(vehicle),category:"OEM Dealer — "+cat.label,lineItems:(task.oemItems||[]).filter((x: any)=>x.accepted).map((x: any)=>({desc:x.desc,price:x.price,costType:x.costType||"ws"})),totalApproved:(task.oemItems||[]).filter((x: any)=>x.accepted).reduce((s: any,x: any)=>s+(Number(x.price)||0),0),startedDate:new Date().toISOString().split("T")[0]});}}>🔧 Work Started</button>}
{task.oemDropDate&&!task.oemWarranty&&!task.oemPaidRepair&&!task.oemWorkStarted&&<div style={{fontSize:13,color:"#6B7280",textAlign:"center",marginTop:8}}>Select Paid Repair, Warranty, or both to proceed</div>}
{task.oemWorkStarted&&!task.oemPickedUp&&<div style={{padding:10,marginTop:8,borderRadius:6,background:"#3B2F10",border:"1px solid #78590A"}}>
<div style={{fontSize:14,color:"#FBBF24",fontWeight:700}}>🔧 Work In Progress — Started: {fmtDate(task.oemWorkStartedDate)}</div>
<button style={{...S.btn,width:"100%",background:"#166534",color:"#6EE7B7",padding:12,fontSize:16,marginTop:8}} onClick={(e: any)=>{e.target.disabled=true;onUpdateTask({oemPickedUp:true,oemPickedUpDate:new Date().toISOString().split("T")[0],status:"complete",dateCompleted:new Date().toISOString().split("T")[0]});if(typeof onCmp==="function")onCmp();
if(typeof fireEmail==="function")fireEmail("buyer_work_complete",{buyer:vehicle?.buyingBroker||"Buyer",vendor:{name:task.oemDealer||"OEM Dealer"},vehicle:vData(vehicle),category:"OEM Dealer — "+(task.oemDealer||""),lineItems:[...(task.oemItems||[]).filter((x: any)=>x.accepted).map((x: any)=>({desc:x.desc,price:x.price,costType:x.costType||"ws"})),...(task.oemWarranty?[{desc:"🛡️ WARRANTY: "+(task.oemWarrantyNotes||"Warranty covered"),price:0,costType:"ws"}]:[])],totalCost:(task.oemItems||[]).filter((x: any)=>x.accepted).reduce((s: any,x: any)=>s+(Number(x.price)||0),0)});}}>✅ Picked Up — Work Complete</button>
</div>}
{task.oemPickedUp&&<div style={{padding:10,marginTop:8,borderRadius:6,background:"#0D3B1E",border:"1px solid #166534"}}>
<div style={{fontSize:14,color:"#34D399",fontWeight:700}}>✅ Picked Up: {fmtDate(task.oemPickedUpDate)}</div>
</div>}
</div>}

{!isOEM&&(task.vendors||[]).length>0&&<div style={{marginBottom:12}}>
<div style={{fontSize:13,fontWeight:700,color:"#9CA3AF",marginBottom:8}}>VENDOR BIDS</div></div>}
{!isOEM&&(task.vendors||[]).filter((vn: any)=>{if(!isVendor||!currentUser)return true;const ce=(currentUser.email||"").toLowerCase();const cf=(currentUser.first_name||currentUser.firstName||"").toLowerCase();const cn=((currentUser.first_name||currentUser.firstName||"")+" "+(currentUser.last_name||currentUser.lastName||"")).trim().toLowerCase();const ve=(vn.email||"").toLowerCase();const vname=(vn.name||"").toLowerCase();return (ce&&ve&&ce===ve)||(cn&&vname&&cn===vname)||(cf&&vname&&cf===vname)||(cf&&vname&&vname.includes(cf));}).map((vn: any,i: any)=>{const bidTotal=(vn.lineItems||[]).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const lt=vn.bidLocked?(vn.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined).reduce((s: any,x: any)=>s+(Number(x.price)||0),0):bidTotal;const wt=task.workTasks||[];const ap=wt.length>0&&wt.every((w: any)=>{const li=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return li&&(Number(li.price)>0||li.noCharge||li.declined);});
return <div key={i} style={{padding:14,marginBottom:8,borderRadius:8,background:vn.selected?"#0F294088":"rgba(255,255,255,0.03)",border:vn.selected?"2px solid #3B82F6":"1px solid #2A2A3E"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}>
<div style={{display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>
<span style={{fontSize:16,fontWeight:700,color:vn.declined?"#F87171":"#E5E7EB"}}>{vn.name}</span>
{vn.declined&&<span style={{...S.badge,background:"#7F1D1D",color:"#FCA5A5"}}>❌ DECLINED</span>}
{vn.selected&&<span style={{...S.badge,background:"#3B82F6",color:"#FFF"}}>✓ ACCEPTED</span>}
{vn.selected&&vn.bidLocked&&<button style={{fontSize:12,padding:"4px 12px",borderRadius:6,border:editBid?"2px solid #F59E0B":"1px solid #2A2A3E",background:editBid?"#78590A":"transparent",color:editBid?"#FDE68A":"#9CA3AF",cursor:"pointer",fontWeight:700}} onClick={()=>setEditBid(!editBid)}>{editBid?"💾 Done Editing":"✏️ Edit Bid"}</button>}
{lt>=0&&<span style={{fontSize:18,fontWeight:800,color:lt===0&&!vn.bidAdjustment?"#9CA3AF":vn.bidAdjustedDate?"#F59E0B":"#FBBF24"}}>{lt===0&&!vn.bidAdjustment?"$0 (No Charge)":"$"+(lt+(vn.bidAdjustment||0)).toLocaleString()}{vn.bidAdjustedDate&&<span style={{fontSize:11,color:"#9CA3AF",marginLeft:4}}>(was ${bidTotal.toLocaleString()})</span>}</span>}</div>
{!isVendor&&!vn.selected&&!vn.declined&&vn.bidLocked&&!(task.vendors||[]).some((v2: any)=>v2.selected)&&(()=>{const items=vn.lineItems||[];const allDecided=items.every((x: any)=>x.accepted||x.declined);const anyAccepted=items.some((x: any)=>x.accepted);return allDecided&&anyAccepted?<button style={{padding:"10px 20px",borderRadius:6,background:"#166534",color:"#6EE7B7",fontSize:16,fontWeight:700,border:"none",cursor:"pointer"}} onClick={()=>{onSelectVendor&&onSelectVendor(vn.id);setExp(false);}}>✅ Accept Bid</button>:!allDecided?<span style={{fontSize:16,color:"#FBBF24",fontWeight:700,padding:"8px 14px",background:"#3B2F10",borderRadius:6,border:"1px solid #78590A"}}>👆 Accept or Decline each item to continue</span>:null;})()}
{!vn.selected&&!vn.declined&&vn.bidLocked&&(task.vendors||[]).some((v2: any)=>v2.selected)&&<div style={{padding:8,background:"#1A1A2E",borderRadius:6,border:"1px solid #2A2A3E",textAlign:"center"}}><span style={{fontSize:12,color:"#6B7280"}}>🔒 Another vendor accepted</span></div>}
{!vn.declined&&!vn.selected&&task.status!=="complete"&&<button style={{padding:"6px 14px",borderRadius:6,background:"#7F1D1D",color:"#FCA5A5",fontSize:12,fontWeight:700,border:"1px solid #EF4444",cursor:"pointer"}} onClick={()=>{onUpdVendor(vn.id,{declined:true,declinedDate:new Date().toISOString().split("T")[0]});const others=(task.vendors||[]).filter((v2: any)=>v2.id!==vn.id);const allDeclined=others.every((v2: any)=>v2.declined);if(allDeclined){onUpdateTask({status:"declined"});}}}>❌ Decline</button>}
{!vn.selected&&task.status!=="complete"&&task.status!=="started"&&<button style={{padding:"6px 14px",borderRadius:6,background:"transparent",color:"#6B7280",fontSize:12,fontWeight:700,border:"1px solid #4B5563",cursor:"pointer",marginLeft:6}} onClick={()=>{if(!confirm("Remove "+vn.name+" from this recon task? This cannot be undone."))return;const others=(task.vendors||[]).filter((v2: any)=>v2.id!==vn.id);const newStatus=others.length===0?"unassigned":task.status;onUpdateTask({vendors:others,status:newStatus});}}>🗑 Remove</button>}
</div>
<div style={{padding:12,background:"#0D0D1A",borderRadius:8,border:"1px solid #2A2A3E",marginBottom:8}}>
{wt.map((w: any)=>{const li=(vn.lineItems||[]).find((x: any)=>x.id===w.id)||{};const isP=w.isPart;return <div key={w.id} style={{padding:"8px 0",borderBottom:"1px solid #2A2A3E"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<span style={{fontSize:14,color:li.declined?"#FCA5A5":"#E5E7EB",fontWeight:600,textDecoration:li.declined?"line-through":"none"}}>{w.desc||"—"}{isP&&<span style={{...S.badge,background:"#1E3A5F",color:"#93C5FD",fontSize:9,marginLeft:6}}>PART</span>}{li.declined&&<span style={{...S.badge,background:"#7F1D1D",color:"#FCA5A5",fontSize:9,marginLeft:6}}>DECLINED</span>}</span>
{vn.bidLocked?<div style={{display:"flex",alignItems:"center",gap:4,flexWrap:"wrap"}}>
<span style={{fontWeight:700,color:li.declined?"#6B7280":"#FBBF24",textDecoration:li.declined?"line-through":"none"}}>${li.declined?0:Number(li.price)||0}</span>
{!isVendor&&<>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:li.accepted?"2px solid #166534":"1px solid #2A2A3E",cursor:li.costType?"pointer":"not-allowed",fontWeight:700,background:li.accepted?"#166534":"transparent",color:li.accepted?"#6EE7B7":li.costType?"#6B7280":"#4B5563",opacity:li.costType?1:0.5}} onClick={()=>{if(!li.costType)return;const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],accepted:true,declined:false,acceptedDate:new Date().toISOString().split("T")[0]};onUpdVendor(vn.id,{lineItems:items});}}>✅ {li.accepted?"Accepted":"Accept"}</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:li.declined?"2px solid #7F1D1D":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:li.declined?"#7F1D1D":"transparent",color:li.declined?"#FCA5A5":"#6B7280"}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],declined:true,accepted:false};const allDeclined=items.every((x: any)=>x.declined);if(allDeclined){onUpdateTask({status:"unassigned",vendors:[],vendorId:null,vendorName:null});if(typeof fireEmail==="function"&&vehicle)fireEmail("vendor_work_canceled",{vendor:{name:vn.name},vehicle:vData(vehicle),lineItems:items.map((x: any)=>({desc:"❌ "+x.desc,price:0,costType:x.costType||"ws"})),totalRemaining:0});notify&&notify("❌ All items declined — "+vn.name+" removed and notified");}else{onUpdVendor(vn.id,{lineItems:items,cancellationSent:false});}}}>❌ Decline</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:li.costType!=="retail"?"2px solid #1E3A5F":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:li.costType!=="retail"?"#1E3A5F":"transparent",color:li.costType!=="retail"?"#93C5FD":"#6B7280"}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],costType:"ws"};onUpdVendor(vn.id,{lineItems:items});}}>W/S</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:li.costType==="retail"?"2px solid #164E63":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:li.costType==="retail"?"#164E63":"transparent",color:li.costType==="retail"?"#67E8F9":"#6B7280"}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],costType:"retail"};onUpdVendor(vn.id,{lineItems:items});}}>🏪 Retail</button>
</>}
{isVendor&&li.costType&&<span style={{...S.badge,background:li.costType==="retail"?"#164E63":"#1E3A5F",color:li.costType==="retail"?"#67E8F9":"#93C5FD",fontSize:11}}>{li.costType==="retail"?"🏪 RETAIL":"W/S"}</span>}
{isVendor&&li.accepted&&<span style={{...S.badge,background:"#166534",color:"#6EE7B7",fontSize:11}}>✅ Approved</span>}
{isVendor&&li.declined&&<span style={{...S.badge,background:"#7F1D1D",color:"#FCA5A5",fontSize:11}}>❌ Declined</span>}
</div>
:(()=>{const ce=(currentUser?.email||"").toLowerCase();const cf=(currentUser?.first_name||currentUser?.firstName||"").toLowerCase();const cn=((currentUser?.first_name||currentUser?.firstName||"")+" "+(currentUser?.last_name||currentUser?.lastName||"")).trim().toLowerCase();const ve=(vn.email||"").toLowerCase();const vname=(vn.name||"").toLowerCase();const myBid=isVendor&&currentUser&&((ce&&ve&&ce===ve)||(cn&&vname&&cn===vname)||(cf&&vname&&cf===vname)||(cf&&vname&&vname.includes(cf)));return myBid?<div style={{display:"flex",gap:6,alignItems:"center"}}><span style={{fontSize:14,color:"#6B7280"}}>$</span><input type="number" placeholder="0" value={li.price||""} style={{background:"#1A1A2E",border:"1px solid #3B82F6",borderRadius:6,padding:"6px 10px",color:"#FBBF24",fontSize:16,fontWeight:700,width:100,textAlign:"right"}} onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);const newPrice=Number(e.target.value)||0;if(ix>=0)items[ix]={...items[ix],price:newPrice};else items.push({id:w.id,desc:w.desc,price:newPrice,isPart:w.isPart});onUpdVendor(vn.id,{lineItems:items});}}/></div>:<div style={{display:"flex",gap:4,alignItems:"center"}}><span style={{fontSize:13,color:"#6B7280",fontStyle:"italic"}}>Waiting on vendor...</span></div>;})()}
</div>
{(isP||cat.key==="parts")&&vn.selected&&li.accepted&&!li.declined&&<div style={{marginTop:6,padding:8,background:"#0D0D1A",borderRadius:6,border:"1px solid #1E3A5F"}}>
<div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap",marginBottom:4}}>
{!li.partApproved?<button style={{...S.btn,fontSize:11,padding:"4px 10px",background:"#1E3A5F"}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partApproved:true,partApprovedDate:new Date().toISOString().split("T")[0],partPrice:items[ix].price||0};onUpdVendor(vn.id,{lineItems:items});}}>Approve Part</button>
:<span style={{fontSize:12,color:"#34D399",fontWeight:600}}>✅ Approved {fmtDate(li.partApprovedDate)}</span>}
</div>
{li.partApproved&&<div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}>
<div style={{display:"flex",alignItems:"center",gap:4}}>
<span style={{fontSize:12,color:li.partOrdered?"#93C5FD":"#6B7280",fontWeight:600}}>Ordered:</span>
{li.partOrdered?<span style={{fontSize:12,color:"#93C5FD"}}>{fmtDate(li.partOrderedDate)}</span>
:<input style={{...S.fi,fontSize:12,padding:"3px 6px",width:110}} type="date" onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partOrdered:true,partOrderedDate:e.target.value};onUpdVendor(vn.id,{lineItems:items});}}/>}
</div>
<div style={{display:"flex",alignItems:"center",gap:4}}>
<span style={{fontSize:12,color:li.partArrived?"#34D399":"#6B7280",fontWeight:600}}>Arrived:</span>
{li.partArrived?<span style={{fontSize:12,color:"#34D399"}}>{fmtDate(li.partArrivedDate)}</span>
:li.partOrdered?<input style={{...S.fi,fontSize:12,padding:"3px 6px",width:110}} type="date" onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partArrived:true,partArrivedDate:e.target.value};onUpdVendor(vn.id,{lineItems:items});}}/>
:<span style={{fontSize:12,color:"#4B5563"}}>--</span>}
</div>
<div style={{display:"flex",alignItems:"center",gap:4}}>
<span style={{fontSize:12,color:li.partInstalled?"#34D399":"#6B7280",fontWeight:600}}>Installed:</span>
{li.partInstalled?<span style={{fontSize:12,color:"#34D399"}}>{fmtDate(li.partInstalledDate)}</span>
:li.partArrived?<input style={{...S.fi,fontSize:12,padding:"3px 6px",width:110}} type="date" onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partInstalled:true,partInstalledDate:e.target.value};onUpdVendor(vn.id,{lineItems:items});}}/>
:<span style={{fontSize:12,color:"#4B5563"}}>--</span>}
</div>
</div>}
</div>}
</div>;})}
{wt.length>0&&<div style={{marginTop:10,paddingTop:10,borderTop:"2px solid #2A2A3E"}}>
<div style={{fontSize:16,fontWeight:800,color:"#E5E7EB"}}>Total: <span style={{color:vn.bidAdjustedDate?"#F59E0B":"#FBBF24",fontSize:20}}>${(lt+(vn.bidAdjustment||0)).toLocaleString()}</span>{vn.bidAdjustedDate&&<span style={{fontSize:12,color:"#9CA3AF",marginLeft:6}}>(original ${lt.toLocaleString()})</span>}</div>
{(()=>{const items=vn.lineItems||[];const wsTotal=items.filter((x: any)=>x.accepted&&x.costType!=="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const retailTotal=items.filter((x: any)=>x.accepted&&x.costType==="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);return (wsTotal>0||retailTotal>0)?<div style={{display:"flex",gap:12,marginTop:6}}>
{wsTotal>0&&<span style={{fontSize:13,color:"#93C5FD",fontWeight:600}}>W/S: ${wsTotal.toLocaleString()}</span>}
{retailTotal>0&&<span style={{fontSize:13,color:"#67E8F9",fontWeight:600}}>🏪 Retail: ${retailTotal.toLocaleString()}</span>}
</div>:null;})()}
</div>}</div>
{editBid&&<div style={{padding:14,marginTop:8,borderRadius:8,background:"#3B2F10",border:"2px solid #F59E0B"}}>
<div style={{fontSize:16,fontWeight:800,color:"#F59E0B",marginBottom:10}}>✏️ Adjust Bid</div>
<div style={{fontSize:14,color:"#E5E7EB",marginBottom:8}}>Original Bid: <b style={{color:"#FBBF24",fontSize:18}}>${bidTotal.toLocaleString()}</b></div>
<label style={{...S.fl,fontSize:14}}>Adjustment Amount (+/-)<input style={{...S.fi,fontSize:20,padding:"12px 14px",textAlign:"center",border:"2px solid #F59E0B",background:"#1A1A2E"}} type="number" placeholder="e.g. -200 or +300" value={vn.bidAdjustment===0?"":vn.bidAdjustment||""} onChange={(e: any)=>{const val=e.target.value===""?0:parseFloat(e.target.value);onUpdVendor(vn.id,{bidAdjustment:val});}}/></label>
{vn.bidAdjustment&&<div style={{fontSize:18,fontWeight:800,textAlign:"center",padding:10,marginTop:6,borderRadius:6,background:vn.bidAdjustment>0?"#1E3A5F":"#3B1515",border:vn.bidAdjustment>0?"1px solid #3B82F6":"1px solid #7F1D1D"}}>
<span style={{color:vn.bidAdjustment>0?"#60A5FA":"#F87171"}}>{vn.bidAdjustment>0?"+":""}{vn.bidAdjustment}</span>
<span style={{color:"#E5E7EB",marginLeft:8}}>= New Total: <b style={{color:"#FBBF24"}}>${(bidTotal+(vn.bidAdjustment||0)).toLocaleString()}</b></span>
</div>}
<label style={{...S.fl,fontSize:14,marginTop:10}}>Reason for Adjustment *<textarea style={{...S.fi,fontSize:14,minHeight:60,resize:"vertical",width:"100%",boxSizing:"border-box"}} placeholder="Required — e.g. poor work, scope change, negotiated down, additional work needed..." value={vn.editReason||""} onChange={(e: any)=>onUpdVendor(vn.id,{editReason:e.target.value})}/></label>
{vn.editReason?<button style={{...S.btn,fontSize:15,padding:"10px 18px",background:"#78590A",color:"#FDE68A",marginTop:8,width:"100%"}} onClick={()=>{const adj=vn.bidAdjustment||0;const newEst=bidTotal+adj;onUpdVendor(vn.id,{bidAdjustedDate:new Date().toISOString().split("T")[0],estimate:newEst,bidOriginal:vn.bidOriginal||bidTotal,bidAdjustment:adj});setEditBid(false);}}>💾 Save Adjustment</button>
:<div style={{fontSize:13,color:"#F87171",marginTop:8,textAlign:"center"}}>⚠️ Reason required to save adjustment</div>}
</div>}
{vn.bidAdjustedDate&&!editBid&&<div style={{padding:10,marginTop:6,borderRadius:6,background:"#3B2F10",border:"1px solid #78590A"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<span style={{color:"#F59E0B",fontWeight:700,fontSize:14}}>✏️ Bid Adjusted {fmtDate(vn.bidAdjustedDate)}</span>
<span style={{fontSize:14,color:vn.bidAdjustment>0?"#60A5FA":"#F87171",fontWeight:700}}>{vn.bidAdjustment>0?"+":""}{vn.bidAdjustment||0}</span>
</div>
<div style={{fontSize:13,color:"#9CA3AF",marginTop:2}}>Original: ${vn.bidOriginal||bidTotal} → Adjusted: ${vn.estimate||bidTotal}</div>
{vn.editReason&&<div style={{fontSize:13,color:"#FDE68A",marginTop:4,fontStyle:"italic"}}>"{vn.editReason}"</div>}
</div>}
{!vn.bidLocked&&<div style={{padding:10,background:"#0D0D1A",borderRadius:8,border:"1px solid #3B82F6",marginBottom:8}}>
{isVendor?<label style={{...S.fl,fontSize:15,fontWeight:700}}>📅 ETA Completion Date *<DateIn style={{fontSize:16,padding:"10px 12px",marginTop:4}} value={vn.etaDone||""} onChange={(v2: any)=>onUpdVendor(vn.id,{etaDone:v2})}/></label>:vn.etaDone?<div style={{...S.fl,fontSize:14}}><span style={{color:"#9CA3AF"}}>📅 Vendor ETA:</span> <b style={{color:"#60A5FA"}}>{fmtDate(vn.etaDone)}</b></div>:<div style={{...S.fl,fontSize:13,color:"#6B7280",fontStyle:"italic"}}>📅 Vendor will set completion date when bidding</div>}
</div>}
{((wt.filter((w: any)=>w.isPart).length>0)||(cat.key==="parts"&&wt.length>0))&&vn.selected&&(()=>{const pts=(cat.key==="parts"?wt:wt.filter((w: any)=>w.isPart)).filter((w: any)=>{const li9=(vn.lineItems||[]).find((x: any)=>x.id===w.id)||{};return !li9.declined&&li9.accepted;});if(pts.length===0)return null;const arrived=pts.filter((w: any)=>{const li=(vn.lineItems||[]).find((x: any)=>x.id===w.id)||{};return li.partArrived;}).length;const allIn=pts.length>0&&arrived===pts.length;return <div style={{padding:12,background:"#1A1A2E",borderRadius:8,marginBottom:8}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}>
<span style={{fontSize:14,fontWeight:700,color:"#93C5FD"}}>📦 Parts Tracking</span>
<span style={{...S.badge,background:allIn?"#166534":"#78590A",color:allIn?"#34D399":"#FDE68A",fontSize:12,padding:"4px 10px"}}>{allIn?"✅ ALL PARTS DELIVERED":arrived+" of "+pts.length+" delivered"}</span>
</div>
{pts.map((w: any)=>{const li=(vn.lineItems||[]).find((x: any)=>x.id===w.id)||{};return <div key={w.id} style={{padding:10,marginBottom:6,borderRadius:6,background:"#0D0D1A",border:`1px solid ${li.partInstalled?"#166534":li.partArrived?"#3B82F6":"#2A2A3E"}`}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}>
<span style={{fontSize:14,fontWeight:700,color:"#E5E7EB"}}>{w.desc}</span>
{li.partPrice>0&&<span style={{fontSize:14,fontWeight:700,color:"#FBBF24"}}>${li.partPrice}</span>}
</div>
<div style={{display:"flex",gap:6,alignItems:"center",marginBottom:6}}>
<label style={{...S.fl,fontSize:13,flex:1}}>Part Cost $<input style={{...S.fi,fontSize:14,padding:"6px 10px"}} type="number" placeholder="$" value={li.partPrice||li.price||""} onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partPrice:Number(e.target.value)};onUpdVendor(vn.id,{lineItems:items});}}/></label>
{li.partPrice>0&&!li.partApproved&&<button style={{...S.btn,fontSize:12,background:"#1E3A5F",padding:"6px 12px",whiteSpace:"nowrap"}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partApproved:true,partApprovedDate:new Date().toISOString().split("T")[0]};onUpdVendor(vn.id,{lineItems:items});}}>Approve</button>}
{li.partApproved&&<span style={{...S.badge,background:"#166534",color:"#34D399",fontSize:11}}>✅ Approved {fmtDate(li.partApprovedDate)}</span>}
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6}}>
<div style={{padding:6,borderRadius:4,background:li.partOrdered?"#1E3A5F":"transparent",border:`1px solid ${li.partOrdered?"#3B82F6":"#2A2A3E"}`,textAlign:"center"}}>
<label style={{fontSize:12,color:li.partOrdered?"#93C5FD":"#6B7280",fontWeight:600,cursor:"pointer"}}><input type="checkbox" checked={li.partOrdered||false} onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partOrdered:e.target.checked,partOrderedDate:e.target.checked?new Date().toISOString().split("T")[0]:""};onUpdVendor(vn.id,{lineItems:items});}}/> Ordered</label>
{li.partOrdered&&<div style={{fontSize:10,color:"#93C5FD"}}>{fmtDate(li.partOrderedDate)}</div>}
</div>
<div style={{padding:6,borderRadius:4,background:li.partArrived?"#0D3B1E":"transparent",border:`1px solid ${li.partArrived?"#166534":"#2A2A3E"}`,textAlign:"center"}}>
<label style={{fontSize:12,color:li.partArrived?"#34D399":"#6B7280",fontWeight:600,cursor:"pointer"}}><input type="checkbox" checked={li.partArrived||false} onChange={(e: any)=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);const checked=e.target.checked;const today=new Date().toISOString().split("T")[0];if(ix>=0)items[ix]={...items[ix],partArrived:checked,partArrivedDate:checked?today:"",partStatus:checked?"received":items[ix].partStatus};onUpdVendor(vn.id,{lineItems:items});}}/> Arrived</label>
{li.partArrived&&<div style={{fontSize:10,color:"#34D399"}}>{fmtDate(li.partArrivedDate)}</div>}
</div>
<div style={{padding:6,borderRadius:4,background:li.partInstalled?"#166534":"transparent",border:`1px solid ${li.partInstalled?"#34D399":"#2A2A3E"}`,textAlign:"center"}}>
{li.partInstalled?<div><div style={{fontSize:12,color:"#FFF",fontWeight:600}}>✅ Installed</div><div style={{fontSize:10,color:"#34D399"}}>{fmtDate(li.partInstalledDate)}</div></div>
:li.partArrived?<button style={{fontSize:12,padding:"4px 8px",background:"#16A34A",color:"#FFF",border:"none",borderRadius:4,cursor:"pointer",width:"100%",fontWeight:700}} onClick={()=>{const items=[...(vn.lineItems||[])];const ix=items.findIndex((x: any)=>x.id===w.id);if(ix>=0)items[ix]={...items[ix],partInstalled:true,partInstalledDate:new Date().toISOString().split("T")[0]};onUpdVendor(vn.id,{lineItems:items});}}>🔧 Install</button>
:<span style={{fontSize:11,color:"#4B5563"}}>—</span>}
</div>
</div>
</div>;})}</div>;})()}
<div style={{padding:10,background:"#1A1A2E",borderRadius:8,marginBottom:8}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}>
<span style={{fontSize:18,fontWeight:700,color:"#F97316"}}>🔍 Findings</span>
<button style={{...S.btn,fontSize:14,padding:"8px 16px",background:"#92400E",color:"#FDE68A"}} onClick={()=>onUpdVendor(vn.id,{vendorFindings:[...(vn.vendorFindings||[]),{id:`vf${Date.now()}`,desc:"",price:0,notes:"",approved:false}],findingsSubmitted:false,findingsDecisionSent:false})}>+ Add</button></div>
{(vn.vendorFindings||[]).map((vf: any,vfi: any)=><div key={vf.id} style={{padding:6,marginBottom:4,borderRadius:6,background:vf.approved?"#0D3B1E":"#3B2F10",border:`1px solid ${vf.approved?"#166534":"#78590A"}`}}>
{vf.declined?<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",opacity:0.5}}><span style={{color:"#FCA5A5",fontSize:14,fontWeight:600,textDecoration:"line-through"}}>{vf.desc}</span><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{color:"#6B7280",fontWeight:700,fontSize:15}}>${vf.price||0}</span><span style={{...S.badge,background:"#7F1D1D",color:"#FCA5A5",fontSize:11}}>❌ DECLINED</span><button style={{fontSize:10,padding:"2px 6px",borderRadius:4,background:"#1A1A2E",color:"#6B7280",border:"none",cursor:"pointer"}} onClick={()=>{const f2=[...(vn.vendorFindings||[])];f2[vfi]={...f2[vfi],declined:false};onUpdVendor(vn.id,{vendorFindings:f2});}}>Undo</button></div></div>
:vf.approved?<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:"#E5E7EB",fontSize:14,fontWeight:600}}>{vf.desc}</span><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{color:"#FBBF24",fontWeight:700,fontSize:15}}>${vf.price||0}</span><span style={{...S.badge,background:vf.findingCostType==="retail"?"#164E63":"#1E3A5F",color:vf.findingCostType==="retail"?"#67E8F9":"#93C5FD",fontSize:10}}>{vf.findingCostType==="retail"?"🏪 Retail":"W/S"}</span><span style={{...S.badge,background:"#166534",color:"#34D399",fontSize:11}}>✅</span><button style={{fontSize:10,padding:"2px 6px",borderRadius:4,background:"#7F1D1D",color:"#FCA5A5",border:"none",cursor:"pointer"}} onClick={()=>{const f2=[...(vn.vendorFindings||[])];f2[vfi]={...f2[vfi],approved:false};onUpdVendor(vn.id,{vendorFindings:f2});}}>Undo</button></div></div>
:<div><div style={{display:"flex",gap:4,marginBottom:4}}>
<input style={{...S.fi,fontSize:12,flex:1}} placeholder="Work found" value={vf.desc} onChange={(e: any)=>{const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],desc:e.target.value};onUpdVendor(vn.id,{vendorFindings:f});}}/>
<input style={{...S.fi,fontSize:12,width:70}} type="number" placeholder="$" value={vf.price||""} onChange={(e: any)=>{const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],price:Number(e.target.value)};onUpdVendor(vn.id,{vendorFindings:f});}}/>
<button style={{background:"none",border:"none",color:"#6B7280",cursor:"pointer",fontSize:12}} onClick={()=>onUpdVendor(vn.id,{vendorFindings:(vn.vendorFindings||[]).filter((_: any,j: any)=>j!==vfi)})}>🗑</button></div>
{vf.desc&&vf.price>0&&<div style={{display:"flex",gap:4,alignItems:"center"}}>
{vn.findingsSubmitted?<div style={{display:"flex",gap:4,flexWrap:"wrap"}}>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:vf.approved?"2px solid #166534":"1px solid #2A2A3E",cursor:vf.findingCostType?"pointer":"not-allowed",fontWeight:700,background:vf.approved?"#166534":"transparent",color:vf.approved?"#6EE7B7":vf.findingCostType?"#6B7280":"#4B5563",opacity:vf.findingCostType?1:0.5}} onClick={()=>{if(!vf.findingCostType)return;const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],approved:true};onUpdVendor(vn.id,{vendorFindings:f});}}>✅ {vf.approved?"Accepted":"Accept"}</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:vf.declined?"2px solid #7F1D1D":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:vf.declined?"#7F1D1D":"transparent",color:vf.declined?"#FCA5A5":"#6B7280"}} onClick={()=>{const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],declined:true,approved:false};onUpdVendor(vn.id,{vendorFindings:f});}}>❌ Decline</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:vf.findingCostType!=="retail"&&vf.findingCostType?"2px solid #1E3A5F":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:vf.findingCostType!=="retail"&&vf.findingCostType?"#1E3A5F":"transparent",color:vf.findingCostType!=="retail"&&vf.findingCostType?"#93C5FD":"#6B7280"}} onClick={()=>{const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],findingCostType:"ws"};onUpdVendor(vn.id,{vendorFindings:f});}}>W/S</button>
<button style={{fontSize:13,padding:"6px 14px",borderRadius:6,border:vf.findingCostType==="retail"?"2px solid #164E63":"1px solid #2A2A3E",cursor:"pointer",fontWeight:700,background:vf.findingCostType==="retail"?"#164E63":"transparent",color:vf.findingCostType==="retail"?"#67E8F9":"#6B7280"}} onClick={()=>{const f=[...(vn.vendorFindings||[])];f[vfi]={...f[vfi],findingCostType:"retail"};onUpdVendor(vn.id,{vendorFindings:f});}}>🏪 Retail</button>
</div>:<div style={{fontSize:11,color:"#6B7280",marginTop:4}}>Submit findings for buyer review</div>}
</div>}
{(!vf.desc||!vf.price)&&<div style={{fontSize:11,color:"#6B7280"}}>Enter description and cost first</div>}
</div>}</div>)}</div>
<div style={{padding:10,background:"#1A1A2E",borderRadius:8,marginBottom:8}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}>
<span style={{fontSize:13,fontWeight:700,color:"#60A5FA"}}>📷 Vendor Photos ({(vn.vendorPhotos||[]).length})</span>
<label style={{...S.btn,fontSize:12,padding:"4px 10px",background:"#1E3A5F",cursor:"pointer"}}><input type="file" multiple style={{display:"none"}} onChange={async (e: any)=>{const files=Array.from(e.target.files||[]);if(!files.length)return;const np:any[]=await Promise.all((files as File[]).map(async(f:File)=>{const isVid=f.type.startsWith("video");if(isVid)return {data:await uploadVid(f),name:f.name,type:"video"};return {data:"pending",blob:f,name:f.name,type:"image"};}));const imgs=np.filter(x=>x.type==="image");const vids=np.filter(x=>x.type==="video");if(imgs.length===0){onUpdVendor(vn.id,{vendorPhotos:[...(vn.vendorPhotos||[]),...vids]});e.target.value="";return;}await Promise.all(imgs.map((item: any)=>new Promise(r=>{const rd=new FileReader();rd.onload=()=>{item.data=rd.result;r(item);};rd.readAsDataURL(item.blob);})));onUpdVendor(vn.id,{vendorPhotos:[...(vn.vendorPhotos||[]),...imgs,...vids]});e.target.value="";}}/>📷 Upload Photo/Video</label></div>
{(vn.vendorPhotos||[]).length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{(vn.vendorPhotos||[]).map((p: any,pi: any)=><div key={pi} style={{width:50,height:50,borderRadius:4,overflow:"hidden",border:"1px solid #2A2A3E",cursor:"pointer",position:"relative"}} onClick={()=>setLbImg(p)}>{p.type==="video"?<div style={{width:"100%",height:"100%",background:"#0D0D1A",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:18}}>🎬</span></div>:<img src={p.data} style={{width:"100%",height:"100%",objectFit:"cover"}}/>}</div>)}</div>}</div>
{!vn.bidLocked&&ap&&vn.etaDone&&<div style={{background:"#78590A",borderRadius:8,overflow:"hidden"}}>
<div style={{padding:"8px 12px"}}>{wt.map((w: any)=>{const li2=(vn.lineItems||[]).find((x: any)=>x.id===w.id);return <div key={w.id} style={{display:"flex",justifyContent:"space-between",padding:"3px 0",fontSize:13,color:"#FDE68A"}}><span>{w.desc}</span><span style={{fontWeight:700}}>${Number(li2?.price)||0}</span></div>;})}</div>
<button style={{...S.btn,width:"100%",background:"#92700A",color:"#FDE68A",borderRadius:0,fontSize:16,padding:12}} onClick={()=>{onUpdVendor(vn.id,{bidLocked:true,estimate:bidTotal},{status:"estimated",estimate:bidTotal});
if(typeof fireEmail==="function"&&vehicle){const items=(vn.lineItems||[]).map((x: any)=>({desc:x.desc,price:x.price,costType:x.costType||"ws",isPart:x.isPart}));fireEmail("buyer_bid_submitted",{buyer:vehicle.buyingBroker||"Buyer",vendor:{name:vn.name},vehicle:vData(vehicle),category:cat.label,categoryKey:cat.key,lineItems:items,totalBid:bidTotal});}setExp(false);}}>Submit Bid — ${bidTotal.toLocaleString()}</button>
</div>}
{vn.bidLocked&&<div style={{marginTop:6}}><div style={{...S.badge,background:"#78590A",color:"#FDE68A",padding:"6px 12px",display:"inline-block"}}>🔒 BID ${(lt+(vn.bidAdjustment||0)).toLocaleString()}</div>
{(()=>{const vfList=vn.vendorFindings||[];const allReady=vfList.length>0&&vfList.every((x: any)=>x.desc&&x.price>0);return vfList.length>0&&!vn.findingsSubmitted?<button style={{...S.btn,width:"100%",background:"#92400E",color:"#FDE68A",padding:10,fontSize:14,marginTop:8,border:"2px solid #F59E0B",opacity:allReady?1:0.4}} disabled={!allReady} onClick={()=>{if(!allReady){notify&&notify("⚠️ All findings need description and price");return;}onUpdVendor(vn.id,{findingsSubmitted:true,findingsSubmittedDate:new Date().toISOString().split("T")[0]});if(typeof fireEmail==="function"&&vehicle){const origItems=(vn.lineItems||[]).filter((x: any)=>x.accepted);const origTotal=origItems.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const findItems=vn.vendorFindings||[];const findTotal=findItems.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);fireEmail("buyer_bid_submitted",{buyer:vehicle.buyingBroker||"Buyer",vendor:{name:vn.name},vehicle:vData(vehicle),category:cat.label+" — FINDINGS",categoryKey:cat.key,lineItems:[...origItems.map((x: any)=>({desc:x.desc,price:x.price,costType:x.costType||"ws"})),...findItems.map((x: any)=>({desc:"🔍 "+x.desc,price:x.price,costType:"ws"}))],totalBid:origTotal+findTotal});}setExp(false);}}>🔍 Submit Findings</button>:null;})()}
{vn.findingsSubmitted&&<div style={{fontSize:12,color:"#F59E0B",marginTop:4}}>🔍 Findings submitted {fmtDate(vn.findingsSubmittedDate)}</div>}
{(()=>{const declinedItems=(vn.lineItems||[]).filter((x: any)=>x.declined);const activeItems=(vn.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined);if(declinedItems.length===0)return null;const alreadySent=vn.cancellationSent;if(alreadySent)return <div style={{fontSize:12,color:"#FCA5A5",marginTop:6}}>❌ Cancellation notice sent {fmtDate(vn.cancellationSentDate)} — {declinedItems.length} item{declinedItems.length>1?"s":""} canceled</div>;return <button style={{...S.btn,width:"100%",background:"#7F1D1D",color:"#FCA5A5",padding:10,fontSize:14,marginTop:8,border:"2px solid #EF4444"}} onClick={(e: any)=>{e.target.disabled=true;onUpdVendor(vn.id,{cancellationSent:true,cancellationSentDate:new Date().toISOString().split("T")[0]});if(typeof fireEmail==="function"&&vehicle){fireEmail("vendor_work_canceled",{vendor:{name:vn.name},vehicle:vData(vehicle),lineItems:[...activeItems.map((x: any)=>({desc:"✅ ACTIVE: "+x.desc,price:x.price,costType:x.costType||"ws"})),...declinedItems.map((x: any)=>({desc:"❌ CANCELED: "+x.desc,price:0,costType:x.costType||"ws"}))],totalRemaining:activeItems.reduce((s: any,x: any)=>s+(Number(x.price)||0),0)});}notify&&notify("❌ Cancellation notice sent to "+vn.name);}}>📩 Send Cancellation Notice to {vn.name} — {declinedItems.length} item{declinedItems.length>1?"s":""} canceled</button>;})()}
{(vn.vendorFindings||[]).length>0&&!vn.findingsSubmitted&&!(vn.vendorFindings||[]).every((x: any)=>x.desc&&x.price>0)&&<div style={{fontSize:12,color:"#F87171",marginTop:4}}>⚠️ Each finding needs: description + price</div>}
{(vn.vendorFindings||[]).some((x: any)=>x.approved)&&<div style={{marginTop:4,fontSize:14,color:"#F97316",fontWeight:700}}>+ Findings: ${(vn.vendorFindings||[]).filter((x: any)=>x.approved).reduce((s: any,x: any)=>s+(Number(x.price)||0),0).toLocaleString()}</div>}
{(vn.vendorFindings||[]).some((x: any)=>x.approved)&&<div style={{fontSize:16,fontWeight:800,color:"#FBBF24",marginTop:2}}>Total: ${(lt+(vn.vendorFindings||[]).filter((x: any)=>x.approved).reduce((s: any,x: any)=>s+(Number(x.price)||0),0)).toLocaleString()}</div>}
{(()=>{const vf=vn.vendorFindings||[];if(vf.length===0||!vn.findingsSubmitted)return null;const allDecided=vf.every((x: any)=>x.approved||x.declined);const alreadySent=vn.findingsDecisionSent;if(!allDecided)return <div style={{fontSize:12,color:"#F59E0B",marginTop:6}}>⚠️ Accept or decline all findings before sending decision</div>;if(alreadySent)return <div style={{fontSize:12,color:"#34D399",marginTop:6}}>✅ Decision sent to vendor {fmtDate(vn.findingsDecisionSentDate)}</div>;return <button style={{...S.btn,width:"100%",background:"#1E3A5F",color:"#93C5FD",padding:12,fontSize:15,marginTop:8,border:"2px solid #3B82F6",fontWeight:800}} onClick={(e: any)=>{e.target.disabled=true;const accF=vf.filter((x: any)=>x.approved);const decF=vf.filter((x: any)=>x.declined);const accTotal=accF.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const origItems=(vn.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined);const origTotal=origItems.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);
if(typeof fireEmail==="function"&&vehicle){fireEmail("vendor_bid_accepted",{vendor:{name:vn.name},vehicle:vData(vehicle),lineItems:[...origItems.map((x: any)=>({desc:"✅ "+x.desc,price:x.price,costType:x.costType||"ws"})),...accF.map((x: any)=>({desc:"✅ 🔍 "+x.desc,price:x.price,costType:x.findingCostType||"ws"})),...decF.map((x: any)=>({desc:"❌ "+x.desc+" (DECLINED)",price:0,costType:x.findingCostType||"ws"}))],totalApproved:origTotal+accTotal,approvedBy:vehicle.buyingBroker||"Buyer",approvedDate:new Date().toISOString().split("T")[0]});}
const newTasks=accF.map((f: any,fi: any)=>({id:"wf"+Date.now()+"_"+fi,desc:"🔍 "+f.desc,isPart:false,isFromFinding:true,findingPrice:Number(f.price)||0,findingCostType:f.findingCostType||"ws"}));if(newTasks.length>0){const curWt=[...(task.workTasks||[]),...newTasks];const updatedVn={...vn,findingsDecisionSent:true,findingsDecisionSentDate:new Date().toISOString().split("T")[0],lineItems:[...(vn.lineItems||[]),...newTasks.map((nt: any)=>({id:nt.id,desc:nt.desc,price:nt.findingPrice,accepted:true,costType:nt.findingCostType,isPart:false}))],vendorFindings:[],findingsSubmitted:false};const updatedVendors=(task.vendors||[]).map((v2: any)=>v2.id===vn.id?updatedVn:v2);const taskExtra: any={workTasks:curWt,vendors:updatedVendors};if(task.status==="complete"){const prevTasks=(task.workTasks||[]).map((w: any)=>w.desc).join(", ");const prevCost=origTotal;taskExtra.status="started";taskExtra.dateStarted=new Date().toISOString().split("T")[0];taskExtra.dateCompleted=null;taskExtra.roundPhotoStart=(task.photos||[]).length;taskExtra.completedRounds=[...(task.completedRounds||[]),{tasks:prevTasks,cost:prevCost,date:task.dateCompleted||new Date().toISOString().split("T")[0],vendor:vn.name}];}else if(task.status==="started"){taskExtra.roundPhotoStart=(task.photos||[]).length;}onUpdateTask(taskExtra);}else{onUpdVendor(vn.id,{findingsDecisionSent:true,findingsDecisionSentDate:new Date().toISOString().split("T")[0]});}notify&&notify("📩 Decision sent"+(newTasks.length>0?" — "+newTasks.length+" findings added as tasks":""));}}>📩 Send Findings Decision to Vendor</button>;})()}
</div>}
{!vn.bidLocked&&ap&&!vn.etaDone&&<div style={{fontSize:12,color:"#F87171",padding:6}}>⚠️ Set ETA completion date to submit bid</div>}
{!vn.declined&&!vn.selected&&task.status!=="complete"&&<div style={{marginTop:10,padding:2,background:"#3B1515",borderRadius:8,border:"1px solid #7F1D1D"}}><button style={{...S.btn,width:"100%",background:"#7F1D1D",color:"#FCA5A5",fontSize:14,padding:10,borderRadius:6}} onClick={()=>{onUpdVendor(vn.id,{declined:true,declinedDate:new Date().toISOString().split("T")[0]});const others=(task.vendors||[]).filter((v2: any)=>v2.id!==vn.id);const allDeclined=others.every((v2: any)=>v2.declined);if(allDeclined){onUpdateTask({status:"declined"});}
if(typeof fireEmail==="function"&&vehicle)fireEmail("buyer_vendor_declined",{buyer:vehicle.buyingBroker||"Buyer",vendor:{name:vn.name},vehicle:vData(vehicle),category:cat.label,reason:"Vendor declined the job"});setExp(false);}}>❌ Decline Job</button></div>}
{!vn.selected&&task.status!=="complete"&&task.status!=="started"&&<div style={{marginTop:8,textAlign:"center"}}><button style={{padding:"8px 16px",borderRadius:6,background:"transparent",color:"#6B7280",fontSize:12,fontWeight:700,border:"1px solid #4B5563",cursor:"pointer"}} onClick={()=>{if(!confirm("Remove "+vn.name+" from this recon task? This cannot be undone."))return;const others=(task.vendors||[]).filter((v2: any)=>v2.id!==vn.id);const newStatus=others.length===0?"unassigned":task.status;onUpdateTask({vendors:others,status:newStatus});notify&&notify("🗑 "+vn.name+" removed");}}>🗑 Remove Vendor</button></div>}
{vn.declined&&<div style={{padding:10,background:"#3B1515",borderRadius:6,border:"1px solid #7F1D1D",marginTop:8,textAlign:"center"}}><span style={{fontSize:14,fontWeight:700,color:"#FCA5A5"}}>❌ Vendor Declined — {fmtDate(vn.declinedDate)}</span>
<button style={{...S.sm,color:"#6B7280",marginLeft:8,fontSize:12}} onClick={()=>{onUpdVendor(vn.id,{declined:false,declinedDate:""});if(task.status==="declined")onUpdateTask({status:"assigned"});}}>Undo</button></div>}
</div>;})}
{!isOEM&&(()=>{const hasTasks=(task.workTasks||[]).length>0&&(task.workTasks||[]).every((w: any)=>w.desc&&w.desc.trim().length>0);const hasMedia=photos.length>0;const mediaSkipped=task.mediaSkipped===true;const mediaReady=hasMedia||mediaSkipped;const noVendorYet=(task.vendors||[]).length===0;
return <>
{noVendorYet&&hasTasks&&!mediaReady&&<div style={{padding:14,marginBottom:10,background:"#0F2940",border:"2px solid #1E3A5F",borderRadius:8}}>
<div style={{fontSize:14,fontWeight:700,color:"#93C5FD",marginBottom:8}}>📸 Add photos/video to show issues to vendor?</div>
<div style={{fontSize:12,color:"#9CA3AF",marginBottom:10}}>Vendor will see what they're bidding on. Recommended for body shop, paint, interior damage.</div>
<div style={{display:"flex",gap:6}}>
<label style={{...S.btn,flex:1,cursor:"pointer",textAlign:"center",background:"#1E3A5F",color:"#93C5FD"}}><input type="file" capture="environment" multiple style={{display:"none"}} onChange={hu}/> 📷 Add Photo / 🎬 Video</label>
<button style={{...S.btn,flex:1,background:"#4C1D95",color:"#E9D5FF"}} onClick={()=>{const inp=document.createElement("input");inp.type="file";inp.multiple=true;(inp as any).onchange=hu;inp.click();}}>📁 Browse Files</button>
<button style={{...S.btn,padding:"10px 16px",background:"transparent",color:"#9CA3AF",border:"1px solid #4B5563"}} onClick={()=>onUpdateTask({mediaSkipped:true})}>Skip — No Media</button>
</div></div>}
{(hasMedia||mediaSkipped||(task.vendors||[]).length>0)&&photos.length>0&&<div style={{padding:8,marginBottom:10,background:"#0D0D1A",border:"1px solid #2A2A3E",borderRadius:6}}>
<div style={{fontSize:11,color:"#6B7280",textTransform:"uppercase",fontWeight:700,marginBottom:6,display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<span>📷 Media ({photos.length})</span>
{noVendorYet&&<label style={{...S.sm,color:"#3B82F6",cursor:"pointer"}}><input type="file" multiple style={{display:"none"}} onChange={hu}/> + Add More</label>}
</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(70px,1fr))",gap:4}}>{photos.map((p: any,i: any)=><div key={i} style={{position:"relative",aspectRatio:"1",borderRadius:4,overflow:"hidden",cursor:"pointer"}} onClick={()=>setLbImg(p)}>{p.type==="video"?<div style={{width:"100%",height:"100%",background:"#0D0D1A",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:24}}>🎬</span></div>:<img src={p.data} style={{width:"100%",height:"100%",objectFit:"cover"}}/>}{noVendorYet&&<button style={{position:"absolute",top:1,right:1,width:16,height:16,borderRadius:"50%",background:"rgba(0,0,0,0.8)",border:"none",color:"#F87171",fontSize:10,cursor:"pointer"}} onClick={(e: any)=>{e.stopPropagation();onPhotos(photos.filter((_: any,j: any)=>j!==i));}}>✕</button>}</div>)}</div></div>}
{!isVendor&&(()=>{const canAdd=isGrounded&&hasTasks&&mediaReady;const existingVendorIds=(task.vendors||[]).map((x: any)=>x.id);const availableVendors=vOpts.filter((v: any)=>!existingVendorIds.includes(v.id));return <select style={{...S.sel,width:"100%",marginBottom:10,opacity:canAdd?1:0.5}} defaultValue="" disabled={!canAdd} onChange={(e: any)=>{if(e.target.value){onAssign(e.target.value);}e.target.value="";}}><option value="" disabled>{!isGrounded?"⚠️ Vehicle must be on ground":!hasTasks?"⚠️ Fill in all task descriptions first":!mediaReady?"⚠️ Add media or click Skip first":(task.vendors||[]).length>0?"+ Add Another Vendor for Bidding...":"+ Add Vendor..."}</option>{availableVendors.map((v: any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select>;})()}
{!isVendor&&(task.vendors||[]).length>0&&!(task.vendors||[]).some((v2: any)=>v2.bidLocked)&&<button style={{...S.btn,width:"100%",background:"#166534",color:"#FFF",fontSize:15,padding:12,marginBottom:10,fontWeight:700}} onClick={()=>{setExp(false);notify&&notify("✅ Sent to "+(task.vendors||[]).length+" vendor"+((task.vendors||[]).length>1?"s":"")+" for bidding");}}>✅ Done — Awaiting Vendor Bid{(task.vendors||[]).length>1?"s":""}</button>}
</>;
})()}
{!isOEM&&<div style={{marginBottom:8,borderRadius:6,border:`1px solid ${task.noteUnread?"#F59E0B":"#2A2A3E"}`}}><div style={{padding:"8px 10px",cursor:"pointer",background:task.noteUnread?"rgba(245,158,11,0.1)":"rgba(255,255,255,0.03)"}} onClick={()=>{setNo(!no);setNv(task.notes||"");if(task.noteUnread)onNotes(task.notes||"",true);}}><span style={{fontSize:13,fontWeight:700,color:task.noteUnread?"#F59E0B":"#9CA3AF"}}>{task.noteUnread?"🔔 NEW NOTE":"📝 NOTES"}</span></div>
{no&&<div style={{padding:8,borderTop:"1px solid #2A2A3E"}}><textarea style={{...S.fi,width:"100%",minHeight:60,boxSizing:"border-box"}} value={nv} onChange={(e: any)=>setNv(e.target.value)}/>
<button style={{...S.btn,fontSize:12,marginTop:4}} onClick={()=>{onNotes(nv,false,true);setNo(false);}}>Save</button></div>}</div>}
{!isOEM&&task.status==="assigned"&&<div style={{padding:12,background:"#3B3510",borderRadius:8,border:"2px solid #6B5F0A"}}>
<div style={{fontSize:16,fontWeight:700,color:"#EAB308",marginBottom:4}}>⏳ WAITING ON VENDOR</div>
<div style={{fontSize:13,color:"#9CA3AF"}}>Vendor must price all tasks, set ETA, and submit bid</div></div>}
{!isOEM&&task.status==="estimated"&&<div style={{padding:12,background:"#3B2F10",borderRadius:8,border:"2px solid #78590A"}}>
<div style={{fontSize:16,fontWeight:700,color:"#FBBF24",marginBottom:6}}>💰 BID SUBMITTED</div>
<div style={{fontSize:14,color:"#FDE68A"}}>Waiting for buyer to approve</div>
<div style={{fontSize:13,color:"#9CA3AF",marginTop:4}}>Vendor ETA: {(()=>{const sv2=(task.vendors||[]).find((x: any)=>x.bidLocked);return sv2?.etaDone?fmtDate(sv2.etaDone):"—";})()}</div>
</div>}
{!isOEM&&task.status==="approved"&&<div style={{padding:12,background:"#0D3B1E",borderRadius:8,border:"2px solid #16A34A"}}>
<div style={{fontSize:16,fontWeight:700,color:"#34D399",marginBottom:6}}>✅ BUYER APPROVED</div>
<div style={{fontSize:14,color:"#9CA3AF",marginBottom:8}}>{isVendor?"Click Start Work to begin":"Waiting for vendor to start work"}</div>
{(()=>{const sv2=(task.vendors||[]).find((x: any)=>x.selected);const vendorEta=sv2?.etaDone||"";return vendorEta?<div style={{fontSize:14,color:"#60A5FA",marginBottom:8}}>ETA Completion: <b>{fmtDate(vendorEta)}</b></div>:null;})()}
{isVendor?<button style={{...S.btn,background:"#16A34A",width:"100%",padding:12,fontSize:16}} onClick={()=>{const sv2=(task.vendors||[]).find((x: any)=>x.selected);onStart(sv2?.etaDone||new Date().toISOString().split("T")[0]);}}>🔧 Start Work</button>:<div style={{padding:10,background:"#0D0D1A",borderRadius:6,border:"1px dashed #166534",textAlign:"center",fontSize:13,color:"#6B7280"}}>⏳ Awaiting vendor to start work</div>}
</div>}
{!isOEM&&task.status==="started"&&<div style={{padding:12,background:"#3B2F10",borderRadius:8,border:"1px solid #78590A"}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:16,fontWeight:700,color:"#FBBF24"}}>🔧 WORK IN PROGRESS</span>{task.etaComplete&&<span style={{color:"#60A5FA"}}>ETA: {fmtDate(task.etaComplete)}</span>}</div>
{task.dateStarted&&<div style={{fontSize:13,color:"#9CA3AF"}}>Started: {fmtDate(task.dateStarted)}</div>}
{task.etaComplete&&(()=>{let d=new Date(task.etaComplete);if(d.getFullYear()<100)d.setFullYear(d.getFullYear()+2000);return d<new Date()?<div style={{color:"#F87171",fontWeight:700,marginBottom:4}}>⚠️ PAST DUE — {Math.max(1,~~(((new Date() as any)-(d as any))/864e5))}d late</div>:null;})()}
{cat.key!=="mechanical"&&<div style={{padding:10,background:"#0D0D1A",borderRadius:6,border:"1px solid #2A2A3E",marginBottom:8}}>
<div style={{fontSize:13,fontWeight:700,color:"#E5E7EB",marginBottom:6}}>📷 Finished Work Photos {photos.length>0&&<span style={{color:"#34D399"}}>({photos.length})</span>}</div>
{photos.length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap",marginBottom:6}}>{photos.slice(0,6).map((p: any,i: any)=><div key={i} style={{width:44,height:44,borderRadius:3,overflow:"hidden",border:"1px solid #2A2A3E",cursor:"pointer"}} onClick={()=>setLbImg(p)}>{p.type==="video"?<div style={{width:"100%",height:"100%",background:"#0D0D1A",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:16}}>🎬</span></div>:<img src={p.data} style={{width:"100%",height:"100%",objectFit:"cover"}}/>}</div>)}</div>}
{isVendor?<label style={{...S.btn,fontSize:12,width:"100%",background:"#1E3A5F",cursor:"pointer",textAlign:"center",display:"block"}}><input type="file" multiple style={{display:"none"}} onChange={hu}/> 📷 Upload Finished Photos/Videos</label>:photos.length===0?<div style={{padding:8,fontSize:12,color:"#6B7280",fontStyle:"italic",textAlign:"center"}}>Vendor will upload finished photos when work is done</div>:null}</div>}
{(()=>{const pts=(task.workTasks||[]).filter((w: any)=>w.isPart);const sv2=(task.vendors||[]).find((x: any)=>x.selected);const allPartsIn=pts.length===0||pts.every((w: any)=>{const li2=(sv2?.lineItems||[]).find((x: any)=>x.id===w.id)||{};return li2.declined||li2.partInstalled;});const noPhotosNeeded=cat.key==="mechanical"||cat.key==="oemdealer";const hasInspection=cat.key==="mechanical"&&(task.workTasks||[]).some((w: any)=>w.isInspection);const hasFindings=sv2&&(sv2.vendorFindings||[]).length>0;const noIssues=task.noIssuesFound||false;const mechBlock=hasInspection&&!hasFindings&&!noIssues;const activeTasks=(task.workTasks||[]).filter((w: any)=>{const li9=(sv2?.lineItems||[]).find((x: any)=>x.id===w.id)||{};return !li9.declined;});const taskCount=activeTasks.length;const roundStart=task?.roundPhotoStart||0;const newPhotos=photos.length-roundStart;const photosOk=noPhotosNeeded||(taskCount>0&&newPhotos>=taskCount)||taskCount===0;const canComplete=photosOk&&allPartsIn&&!mechBlock;
return <span style={{display:"contents"}}>{hasInspection&&<div style={{padding:10,marginBottom:8,borderRadius:6,background:noIssues?"#0D3B1E":"#1A1A2E",border:`1px solid ${noIssues?"#166534":"#2A2A3E"}`}}>
<label style={{display:"flex",alignItems:"center",gap:8,fontSize:15,color:noIssues?"#34D399":"#E5E7EB",fontWeight:600,cursor:"pointer"}}><input type="checkbox" style={{width:18,height:18}} checked={noIssues} onChange={(e: any)=>onUpdateTask({noIssuesFound:e.target.checked})}/> ✅ No Issues Found — Vehicle Passed Inspection</label>
</div>}
{isVendor?<button style={{...S.btn,background:canComplete?"#166534":"#4B5563",width:"100%",padding:10,cursor:canComplete?"pointer":"not-allowed",opacity:canComplete?1:0.5}} onClick={(e: any)=>{if(!canComplete)return;e.target.disabled=true;onCmp();setExp(false);}}>✅ Mark Complete</button>:<div style={{padding:10,background:"#0D0D1A",borderRadius:6,border:"1px dashed #166534",textAlign:"center",fontSize:13,color:"#6B7280"}}>⏳ Awaiting vendor to mark complete</div>}
{!photosOk&&!noPhotosNeeded&&<div style={{fontSize:12,color:"#F87171",marginTop:4}}>⚠️ Upload {taskCount} photo{taskCount>1?"s":""} (1 per task) — have {newPhotos} new</div>}
{!allPartsIn&&<div style={{fontSize:12,color:"#F87171",marginTop:4}}>⚠️ All parts must be installed before completing</div>}
{mechBlock&&<div style={{fontSize:12,color:"#F87171",marginTop:4}}>⚠️ Add findings or check "No Issues Found" before completing inspection</div>}</span>;})()}</div>}
{task.status==="complete"&&!task.approvedForPayment&&!isVendor&&<div style={{padding:14,background:"#3B2F10",borderRadius:8,border:"2px solid #F59E0B",marginBottom:10}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}>
<div style={{fontSize:15,fontWeight:800,color:"#FDE68A"}}>⚠️ AWAITING APPROVAL TO PAY</div>
<span style={{padding:"4px 10px",background:vehicle?.location==="Dallas"?"#4C1D95":"#1E3A5F",color:vehicle?.location==="Dallas"?"#C4B5FD":"#93C5FD",borderRadius:6,fontSize:11,fontWeight:700}}>📍 {vehicle?.location||"PHX"}</span>
</div>
<div style={{fontSize:12,color:"#FBBF24",marginBottom:10}}>Vendor marked complete{task.dateCompleted?" on "+fmtDate(task.dateCompleted):""} — review the work and approve to release for payment.</div>
{(()=>{const winnerVn=(task.vendors||[]).find((v2: any)=>v2.selected);if(!winnerVn)return null;const accLines=(winnerVn.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined);const total=accLines.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const ws=accLines.filter((x: any)=>x.costType==="ws"||!x.costType).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const ret=accLines.filter((x: any)=>x.costType==="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);return <div style={{background:"#0D0D1A",borderRadius:6,padding:10,marginBottom:10}}>
{accLines.map((li: any,li_idx: any)=><div key={li_idx} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",fontSize:12,color:"#E5E7EB",borderBottom:li_idx<accLines.length-1?"1px solid #1E1E32":"none"}}>
<span>{li.desc}</span>
<span><span style={{color:li.costType==="retail"?"#67E8F9":"#93C5FD",fontSize:11,marginRight:4}}>{li.costType==="retail"?"Retail":"W/S"}</span><span style={{color:"#FBBF24",fontWeight:700}}>${Number(li.price)||0}</span></span>
</div>)}
<div style={{display:"flex",justifyContent:"space-between",padding:"8px 0 0",marginTop:6,borderTop:"1px solid #166534"}}>
<span style={{color:"#34D399",fontWeight:700,fontSize:13}}>Vendor: {winnerVn.name}</span>
<span style={{color:"#34D399",fontWeight:700,fontSize:16}}>${total.toLocaleString()}</span>
</div>
{(ws>0||ret>0)&&<div style={{fontSize:10,color:"#6B7280",textAlign:"right",marginTop:2}}>W/S: ${ws.toLocaleString()} • Retail: ${ret.toLocaleString()}</div>}
</div>;})()}
<div style={{display:"flex",gap:6}}>
<button style={{...S.btn,flex:1,background:"#166534",color:"#FFF",padding:10,fontSize:14,fontWeight:700}} onClick={()=>{const winnerVn=(task.vendors||[]).find((v2: any)=>v2.selected);if(!winnerVn){notify&&notify("⚠️ No vendor found");return;}const accLines=(winnerVn.lineItems||[]).filter((x: any)=>x.accepted&&!x.declined);const lockedTotal=accLines.reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const lockedWS=accLines.filter((x: any)=>x.costType==="ws"||!x.costType).reduce((s: any,x: any)=>s+(Number(x.price)||0),0);const lockedRetail=accLines.filter((x: any)=>x.costType==="retail").reduce((s: any,x: any)=>s+(Number(x.price)||0),0);onUpdateTask({approvedForPayment:true,approvedPaymentDate:new Date().toISOString().split("T")[0],approvedBy:currentUser?.first_name?currentUser.first_name+" "+(currentUser.last_name||""):"Buyer",lockedTotal:lockedTotal,lockedWS:lockedWS,lockedRetail:lockedRetail,lockedVendorName:winnerVn.name});if(typeof fireEmail==="function"&&vehicle){fireEmail("recon_approved_for_payment",{vehicle:vData(vehicle),buyer:vehicle.buyingBroker,vendor:{name:winnerVn.name,email:winnerVn.email},seller:vehicle.sellingBroker,category:cat.label,categoryKey:cat.key,lineItems:accLines.map((x: any)=>({desc:x.desc,price:x.price,costType:x.costType||"ws"})),lockedTotal,lockedWS,lockedRetail,approvedBy:currentUser?.first_name?currentUser.first_name+" "+(currentUser.last_name||""):"Buyer",approvedDate:new Date().toISOString().split("T")[0],location:vehicle?.location||"PHX"});}notify&&notify("✅ Approved for payment — AP team notified");}}>✅ Approve for Payment</button>
<button style={{...S.btn,background:"#7F1D1D",color:"#FCA5A5",padding:"10px 14px",fontSize:13,fontWeight:700}} onClick={()=>{const reason=prompt("Why are you disputing this work?\n\n(e.g. work incomplete, wrong color, photos don't show finished work)");if(!reason)return;const winnerVn=(task.vendors||[]).find((v2: any)=>v2.selected);onUpdateTask({disputed:true,disputedDate:new Date().toISOString().split("T")[0],disputedReason:reason,disputedBy:currentUser?.first_name?currentUser.first_name+" "+(currentUser.last_name||""):"Buyer",status:"started",dateCompleted:null});if(typeof fireEmail==="function"&&vehicle&&winnerVn){fireEmail("recon_disputed",{vehicle:vData(vehicle),buyer:vehicle.buyingBroker,vendor:{name:winnerVn.name,email:winnerVn.email},seller:vehicle.sellingBroker,category:cat.label,categoryKey:cat.key,reason:reason,disputedBy:currentUser?.first_name?currentUser.first_name+" "+(currentUser.last_name||""):"Buyer",disputedDate:new Date().toISOString().split("T")[0]});}notify&&notify("⚠️ Work disputed — vendor notified");}}>⚠️ Dispute</button>
</div>
</div>}
{task.status==="complete"&&task.approvedForPayment&&!task.paid&&!isVendor&&<div style={{padding:12,background:"#0D3B1E",borderRadius:8,border:"2px solid #166534",marginBottom:10}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div><div style={{fontSize:14,fontWeight:800,color:"#34D399"}}>✅ APPROVED FOR PAYMENT</div>
<div style={{fontSize:11,color:"#6EE7B7",marginTop:2}}>Locked ${(task.lockedTotal||0).toLocaleString()} • Approved by {task.approvedBy} • {fmtDate(task.approvedPaymentDate)}</div></div>
<span style={{padding:"4px 8px",background:"#3B2F10",color:"#FDE68A",borderRadius:6,fontSize:10,fontWeight:700}}>💸 Pending Check</span>
</div>
</div>}
{task.status==="complete"&&task.paid&&!isVendor&&<div style={{padding:12,background:"#0D3B1E",borderRadius:8,border:"2px solid #166534",marginBottom:10}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div><div style={{fontSize:14,fontWeight:800,color:"#34D399"}}>💸 PAID</div>
<div style={{fontSize:11,color:"#6EE7B7",marginTop:2}}>Check #{task.checkNumber} • Paid {fmtDate(task.paidDate)} • ${(task.lockedTotal||0).toLocaleString()}</div></div>
<span style={{padding:"4px 8px",background:"#166534",color:"#6EE7B7",borderRadius:6,fontSize:10,fontWeight:700}}>✓ COMPLETE</span>
</div>
</div>}
{task.status==="complete"&&<div style={{padding:12,background:"#0D3B1E",borderRadius:8}}>
<div style={{textAlign:"center",marginBottom:8}}><span style={{fontSize:18,fontWeight:800,color:"#34D399"}}>✅ COMPLETED</span>
{task.dateStarted&&task.dateCompleted&&<span style={{fontSize:13,color:"#9CA3AF",marginLeft:8}}>({Math.max(1,~~(((new Date(task.dateCompleted) as any)-(new Date(task.dateStarted) as any))/864e5))}d to complete)</span>}</div>
{(task.completedRounds||[]).length>0&&<div style={{marginBottom:8}}>
{(task.completedRounds||[]).map((rd: any,ri: any)=><div key={ri} style={{fontSize:12,color:"#9CA3AF",padding:"4px 8px",background:"#0D0D1A",borderRadius:4,marginBottom:2}}>Round {ri+1}: ✅ {rd.tasks||"completed"} — ${rd.cost||0}{rd.vendor?" — "+rd.vendor:""} — Completed {rd.date?fmtDate(rd.date):""}</div>)}
</div>}
<button style={{...S.btn,width:"100%",background:"#78590A",color:"#FDE68A",padding:10,fontSize:14}} onClick={()=>{onUpdateTask({status:"unassigned",dateCompleted:null,dateStarted:null,workTasks:[],vendors:[],roundPhotoStart:(task.photos||[]).length});
notify&&notify("🔄 Reopened — add tasks and assign vendor");}}>🔄 Reopen — Add More Work</button>
</div>}
</div></div></div>}
{lbImg&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.98)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:9999,cursor:"pointer"}} onClick={()=>setLbImg(null)}>
<div style={{width:"98vw",height:"98vh",display:"flex",alignItems:"center",justifyContent:"center"}} onClick={(e: any)=>e.stopPropagation()}>
{lbImg.type==="video"?<video key={lbImg.data} src={lbImg.data} controls autoPlay playsInline style={{maxWidth:"96vw",maxHeight:"94vh",borderRadius:4,background:"#000"}} onClick={(e: any)=>e.stopPropagation()}/>:<img src={lbImg.data} style={{maxWidth:"96vw",maxHeight:"94vh",borderRadius:4,objectFit:"contain"}}/>}
<button style={{position:"fixed",top:12,right:12,width:48,height:48,borderRadius:"50%",background:"#EF4444",border:"none",color:"#FFF",fontSize:24,cursor:"pointer"}} onClick={()=>setLbImg(null)}>✕</button></div></div>}
</span>;
}
